### ISSUE TITLE
Failing to start with " Error: Cannot find module 'iconv-lite'"

### ISSUE THREAD

**Issue by alf5** [mhutchie/vscode-git-graph#615]
**Describe the Bug**
the extension is failing to start.
in the "Output"  window selecting the "Log (Extension Host)" dropdown the following text appears:

[2022-01-25 08:53:06.658] [exthost] [error] Activating extension mhutchie.git-graph failed due to an error:
[2022-01-25 08:53:06.658] [exthost] [error] Error: Cannot find module 'iconv-lite'
Require stack:
- /home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/dataSource.js
- /home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/gitGraphView.js
- /home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/commands.js
- /home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/extension.js
- /usr/share/code-insiders/resources/app/out/vs/loader.js
- /usr/share/code-insiders/resources/app/out/bootstrap-amd.js
- /usr/share/code-insiders/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32271)
	at Function.p._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28855)
	at Function.g._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:109:60250)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/dataSource.js:16:22)
	at Module.u._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32271)
	at Function.p._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28855)
	at Function.g._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:109:60250)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/gitGraphView.js:16:22)
	at Module.u._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32271)
	at Function.p._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28855)
	at Function.g._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:109:60250)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/commands.js:17:24)
	at Module.u._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32271)
	at Function.p._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28855)
	at Function.g._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:109:60250)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/alfred/.vscode-insiders/extensions/mhutchie.git-graph-1.30.0/out/extension.js:15:20)
	at Module.u._compile (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32271)
	at Function.p._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28855)
	at Function.g._load (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:109:60250)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/usr/share/code-insiders/resources/app/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:30425)
	at v._doActivateExtension (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:13330)
	at v._activateExtension (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:12285)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 4)
	at async Promise.all (index 0)

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Load a folder / workspace

**Expected Behaviour**
Be able to start

**Environment**
 - Git Graph Extension Version: [e.g. 1.13.0]
 - Visual Studio Code Version: [e.g. 1.64.0-insiders]
 - Operating System: [e.g. Ubuntu 21.04]

**Screenshots (optional)**

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @alf5,

This error indicates that one of the extension's dependencies is not available on your file system. It is included within the extensions vsix package.

Very rarely during Visual Studio Code (or extension) installs & updates, Visual Studio Code can fail to correctly unpack the extensions files, causing it to have the issue you've encountered. This can be fixed by reinstalling the extension (preferably by downgrading the extension to the previous version, and then reinstalling the latest version).
